from __future__ import annotations

from typing import Any

CRITIC_GU_NODE_DIM = 15
CRITIC_UAV_NODE_DIM = 19
CRITIC_SAT_NODE_DIM = 18
CRITIC_UAV_GU_EDGE_DIM = 9
CRITIC_UAV_SAT_EDGE_DIM = 18
CRITIC_UAV_UAV_EDGE_DIM = 11
CRITIC_GLOBAL_SCALAR_DIM = 27
CRITIC_UAV_LOCAL_SUM_DIM = 8
CRITIC_SAT_LOCAL_SUM_DIM = 8

CRITIC_EMBED_DIM = 128
CRITIC_EDGE_EMBED_DIM = 128
CRITIC_GLOBAL_EMBED_DIM = 128
CRITIC_SYSTEM_TOKEN_DIM = 128
CRITIC_HIDDEN_DIM = 256
CRITIC_MESSAGE_LAYERS = 1
CRITIC_VALUE_HEAD_HIDDEN = 256

CRITIC_STAGE_ACCEL = 0
CRITIC_STAGE_SAT = 1
CRITIC_STAGE_BW = 2

# GU node fields.
GU_X = 0
GU_Y = 1
GU_QUEUE_STEPS = 2
GU_QUEUE_FILL = 3
GU_EXPECTED_ARRIVAL_STEPS = 4
GU_LAST_ARRIVAL_STEPS = 5
GU_LAST_OUTFLOW_STEPS = 6
GU_LAST_DROP_STEPS = 7
GU_SERVICE_EMA_STEPS = 8
GU_LOCAL_COST_LOG_RATIO = 9
GU_LAST_TOTAL_COST_LOG_RATIO = 10
GU_PREFIX_TOTAL_COST_LOG_RATIO = 11
GU_PREFIX_COST_KNOWN = 12
GU_LAST_WORKLOAD_LOG1P = 13
GU_PREFIX_WORKLOAD_LOG1P = 14

# UAV node fields.
UAV_X = 0
UAV_Y = 1
UAV_VX = 2
UAV_VY = 3
UAV_ENERGY = 4
UAV_QUEUE_STEPS = 5
UAV_QUEUE_FILL = 6
UAV_LAST_INFLOW_STEPS = 7
UAV_LAST_OUTFLOW_STEPS = 8
UAV_LAST_DROP_STEPS = 9
UAV_SERVICE_EMA_STEPS = 10
UAV_LOCAL_COST_LOG_RATIO = 11
UAV_LAST_TOTAL_COST_LOG_RATIO = 12
UAV_PREFIX_TOTAL_COST_LOG_RATIO = 13
UAV_PREFIX_COST_KNOWN = 14
UAV_LAST_WORKLOAD_LOG1P = 15
UAV_PREFIX_WORKLOAD_LOG1P = 16
UAV_PREFIX_BW_VALID_COUNT_FRAC = 17
UAV_LAST_ACCESS_INTERFERENCE_LOG1P = 18

# SAT node fields.
SAT_X = 0
SAT_Y = 1
SAT_Z = 2
SAT_VX = 3
SAT_VY = 4
SAT_VZ = 5
SAT_QUEUE_STEPS = 6
SAT_QUEUE_FILL = 7
SAT_LAST_INCOMING_STEPS = 8
SAT_LAST_PROCESSED_STEPS = 9
SAT_LAST_DROP_STEPS = 10
SAT_SERVICE_EMA_STEPS = 11
SAT_COST_LOG_RATIO = 12
SAT_LAST_WORKLOAD_LOG1P = 13
SAT_PREFIX_SELECTED_LOAD_FRAC = 14
SAT_PREFIX_LOAD_KNOWN = 15
SAT_LAST_SELECTED_LOAD_FRAC = 16
SAT_PROC_CAPACITY_STEPS = 17

# UAV-GU edge fields.
UG_REL_X = 0
UG_REL_Y = 1
UG_HORIZONTAL_DIST = 2
UG_ELEVATION_NORM = 3
UG_ACCESS_SE_REF = 4
UG_LAST_BW_FRACTION = 5
# Legacy name kept for enum/API stability. This slot stores the continuous
# previous BW fraction, not a binary served flag.
UG_LAST_SERVED_FLAG = 6
UG_PREFIX_BW_VALID_FLAG = 7
UG_PREFIX_BW_VALID_KNOWN = 8

# UAV-SAT edge fields.
US_REL_X = 0
US_REL_Y = 1
US_REL_Z = 2
US_REL_VX = 3
US_REL_VY = 4
US_REL_VZ = 5
US_RADIAL_VELOCITY_NORM = 6
US_RANGE_NORM = 7
US_ELEVATION_NORM = 8
US_DOPPLER_NORM = 9
US_DOPPLER_MARGIN = 10
US_BACKHAUL_SE_REF = 11
US_VISIBLE_FLAG = 12
US_VALID_FLAG = 13
US_LAST_SELECTED_FLAG = 14
US_PREFIX_SELECTED_FLAG = 15
US_PREFIX_SELECTED_KNOWN = 16
US_PREFIX_BACKHAUL_CAPACITY_STEPS = 17

# UAV-UAV edge fields.
UU_REL_X = 0
UU_REL_Y = 1
UU_REL_VX = 2
UU_REL_VY = 3
UU_DIST_NORM = 4
UU_CLOSING_SPEED_NORM = 5
UU_ALERT_FLAG = 6
UU_UNSAFE_FLAG = 7
UU_LAST_SHARED_SAT_FRAC = 8
UU_PREFIX_SHARED_SAT_FRAC = 9
UU_PREFIX_SHARED_SAT_KNOWN = 10

# Global scalar fields.
GLOBAL_TOTAL_GU_QUEUE_STEPS = 0
GLOBAL_TOTAL_UAV_QUEUE_STEPS = 1
GLOBAL_TOTAL_SAT_QUEUE_STEPS = 2
GLOBAL_TOTAL_GU_DROP_STEPS = 3
GLOBAL_TOTAL_UAV_DROP_STEPS = 4
GLOBAL_TOTAL_SAT_DROP_STEPS = 5
GLOBAL_TOTAL_EXPECTED_ARRIVAL_STEPS = 6
GLOBAL_TOTAL_LAST_GU_OUTFLOW_STEPS = 7
GLOBAL_TOTAL_LAST_UAV_OUTFLOW_STEPS = 8
GLOBAL_TOTAL_LAST_SAT_PROCESSED_STEPS = 9
GLOBAL_TOTAL_LAST_WEIGHTED_WORKLOAD_STEPS = 10
GLOBAL_TOTAL_PREFIX_WEIGHTED_WORKLOAD_STEPS = 11
GLOBAL_PREFIX_WORKLOAD_KNOWN = 12
GLOBAL_LAST_INTERFERENCE_MEAN = 13
GLOBAL_LAST_INTERFERENCE_MAX = 14
GLOBAL_SELECTED_SAT_LOAD_MEAN = 15
GLOBAL_SELECTED_SAT_LOAD_MAX = 16
GLOBAL_SELECTED_SAT_LOAD_KNOWN = 17
GLOBAL_LAST_SELECTED_SAT_LOAD_MEAN = 18
GLOBAL_LAST_SELECTED_SAT_LOAD_MAX = 19
GLOBAL_NON_TOKEN_SAT_COUNT_FRAC = 20
GLOBAL_NON_TOKEN_SAT_QUEUE_STEPS = 21
GLOBAL_NON_TOKEN_SAT_DROP_STEPS = 22
GLOBAL_NON_TOKEN_SAT_LAST_PROCESSED_STEPS = 23
GLOBAL_NON_TOKEN_SAT_WORKLOAD_STEPS = 24
GLOBAL_NON_TOKEN_SAT_DROP_WORKLOAD_STEPS = 25
GLOBAL_REMAINING_HORIZON_FRAC = 26


def sat_actor_candidate_max_from_cfg(cfg: Any) -> int:
    visible_sats_max = getattr(cfg, "visible_sats_max", None)
    candidate_raw = visible_sats_max if visible_sats_max is not None else getattr(cfg, "sats_obs_max", None)
    if candidate_raw is None:
        raise ValueError("visible_sats_max/sats_obs_max must define a positive SAT candidate count")
    candidate_max = int(candidate_raw)
    if candidate_max <= 0:
        raise ValueError("visible_sats_max/sats_obs_max must define a positive SAT candidate count")
    num_sat = int(getattr(cfg, "num_sat", 0))
    if num_sat <= 0:
        raise ValueError("num_sat must be positive")
    return min(num_sat, candidate_max)


def critic_sat_token_max_from_cfg(cfg: Any) -> int:
    num_uav = int(getattr(cfg, "num_uav", 0))
    if num_uav <= 0:
        raise ValueError("num_uav must be positive")
    num_sat = int(getattr(cfg, "num_sat", 0))
    if num_sat <= 0:
        raise ValueError("num_sat must be positive")
    return min(num_sat, num_uav * sat_actor_candidate_max_from_cfg(cfg))
